// Equipment-granted skills — item procs and set auras (source: equipment)

export const EQUIPMENT_SKILLS = {
  STARLIGHT_SLASH: {
    id: 'STARLIGHT_SLASH', name: 'Starlight Slash', type: 'active', source: 'equipment',
    itemId: 'MYTHRIL_BLADE', unlockLevel: null,
    description: 'Mythril Blade grants a chance for bonus damage.',
    icon: '⚡', effects: { powerMultiplier: 1.4, atkBonus: 0.50, critChance: 0.20 }, procChance: 0.45,
    narrative: 'slashes with starlight from the Mythril Blade!',
  },
  MANA_OVERLOAD: {
    id: 'MANA_OVERLOAD', name: 'Mana Overload', type: 'active', source: 'equipment',
    itemId: 'CRYSTAL_STAFF', unlockLevel: null,
    description: 'Crystal Staff overloads with mana for massive damage.',
    icon: '💥', effects: { powerMultiplier: 1.2, magBonus: 0.60 }, procChance: 0.50,
    narrative: 'channels a Mana Overload through the Crystal Staff!',
  },
  VANISH: {
    id: 'VANISH', name: 'Vanish', type: 'passive', source: 'equipment',
    itemId: 'SHADOW_CHAIN', unlockLevel: null,
    description: 'Shadow Chainmail shrouds the wearer, granting a permanent +20% dodge chance.',
    icon: '👻', effects: { dodgeChance: 0.20 }, procChance: 1.0,
    narrative: null,
  },
  MYTHRIL_BARRIER: {
    id: 'MYTHRIL_BARRIER', name: 'Mythril Barrier', type: 'passive', source: 'equipment',
    itemId: 'MYTHRIL_PLATE', unlockLevel: null,
    description: 'Mythril Plate sustains a permanent protective barrier: +35% DEF.',
    icon: '🛡', effects: { defBonus: 0.35 }, procChance: 1.0,
    narrative: null,
  },
  ARCANE_RESONANCE: {
    id: 'ARCANE_RESONANCE', name: 'Arcane Resonance', type: 'passive', source: 'equipment',
    itemId: 'CRYSTAL_ORB', unlockLevel: null,
    description: 'Crystal Orb grants +15% MAG and +8% accuracy.',
    icon: '✦', effects: { magBonus: 0.15, atkBonus: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  POWER_SURGE: {
    id: 'POWER_SURGE', name: 'Power Surge', type: 'active', source: 'equipment',
    itemId: 'POWER_STONE', unlockLevel: null,
    description: 'Power Stone releases a surge of raw energy.',
    icon: '⚡', effects: { powerMultiplier: 1.5 }, procChance: 0.55,
    narrative: 'unleashes a Power Surge from the stone!',
  },
  POISON_BLADE: {
    id: 'POISON_BLADE', name: 'Poison Blade', type: 'active', source: 'equipment',
    itemId: 'VENOM_FANG', unlockLevel: null,
    description: 'Venom Fang coats attacks in deadly poison.',
    icon: '🐍', effects: { powerMultiplier: 1.2, atkBonus: 0.45, critChance: 0.15 }, procChance: 0.55,
    narrative: 'coats the Venom Fang in deadly poison and strikes!',
  },
  DUAL_THRUST: {
    id: 'DUAL_THRUST', name: 'Dual Thrust', type: 'active', source: 'equipment',
    itemId: 'SHADOW_EDGE', unlockLevel: null,
    description: 'Shadow Edge strikes twice in a single heartbeat.',
    icon: '⚔', effects: { powerMultiplier: 1.4, atkBonus: 0.80, spdBonus: 0.20, critChance: 0.30 }, procChance: 0.50,
    narrative: 'thrusts the Shadow Edge twice in the blink of an eye!',
  },
  STORM_VOLLEY: {
    id: 'STORM_VOLLEY', name: 'Storm Volley', type: 'active', source: 'equipment',
    itemId: 'STORMREND_BOW', unlockLevel: null,
    description: 'Stormrend Bow unleashes a volley of lightning-charged arrows.',
    icon: '⚡', effects: { powerMultiplier: 1.4, atkBonus: 0.70, spdBonus: 0.20, critChance: 0.25 }, procChance: 0.50,
    narrative: 'unleashes a Storm Volley — lightning crackles from every arrow!',
  },
  CLEAVING_STRIKE: {
    id: 'CLEAVING_STRIKE', name: 'Cleaving Strike', type: 'active', source: 'equipment',
    itemId: 'FLAMBERGE', unlockLevel: null,
    description: 'Flamberge cleaves through armor with devastating force.',
    icon: '⚔', effects: { powerMultiplier: 1.4, atkBonus: 0.75, defPierce: 0.30 }, procChance: 0.50,
    narrative: 'brings the Flamberge down in a devastating Cleaving Strike!',
  },
  DRAGON_FIST: {
    id: 'DRAGON_FIST', name: 'Dragon Fist', type: 'active', source: 'equipment',
    itemId: 'DRAGON_CLAW', unlockLevel: null,
    description: 'Dragon Claw channels draconic ki into a devastating strike.',
    icon: '🐉', effects: { powerMultiplier: 1.4, atkBonus: 0.80, spdBonus: 0.25, critChance: 0.25 }, procChance: 0.50,
    narrative: 'channels draconic ki and unleashes a Dragon Fist!',
  },
  HEAVENLY_PALM: {
    id: 'HEAVENLY_PALM', name: 'Retribution Stance', type: 'passive', source: 'equipment',
    itemId: 'CELESTIAL_BO', unlockLevel: null,
    description: 'The Celestial Bo hums with divine energy, creating a constant deflective aura. Incoming blows are turned aside and reflected back, weakening the attacker.',
    icon: '✨', effects: { isDeflect: true, deflectChance: 0.20, dmgReduction: 0.30, reflectPct: 0.20, atkDebuff: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  DIVINE_GRACE_EQ: {
    id: 'DIVINE_GRACE_EQ', name: 'Staff of Grace', type: 'active', source: 'equipment',
    itemId: 'DIVINE_STAFF', unlockLevel: null,
    description: 'The Divine Staff channels holy energy, bolstering the party.',
    icon: '🌟', effects: { powerMultiplier: 1.4, magBonus: 0.40, healBonus: 0.25 }, procChance: 0.55,
    narrative: 'channels the Staff of Grace — holy energy surges forth!',
  },
  HOLY_SMITE: {
    id: 'HOLY_SMITE', name: 'Holy Smite', type: 'active', source: 'equipment',
    itemId: 'TEMPLARS_FLAIL', unlockLevel: null,
    description: 'Calls down holy wrath through the flail, smiting a single foe. Scales with DEF.',
    icon: '✝', effects: { powerMultiplier: 1.4, atkBonus: 0.35, defScaling: 0.45, defBonus: 0.20, maxHpBonus: 0.05 }, procChance: 0.45,
    narrative: 'calls down holy wrath — the flail strikes with divine force!',
  },
  DIVINE_JUDGEMENT: {
    id: 'DIVINE_JUDGEMENT', name: 'Divine Judgement', type: 'active', source: 'equipment',
    itemId: 'JUDGEMENT', unlockLevel: null,
    description: 'Delivers the final verdict — divine wrath crashes down on the target. Scales with DEF.',
    icon: '⚖', effects: { powerMultiplier: 1.6, atkBonus: 0.45, defScaling: 0.50, defBonus: 0.30, maxHpBonus: 0.10, critBonus: 0.15 }, procChance: 0.60,
    narrative: 'delivers Divine Judgement — holy wrath crashes down!',
  },
  GUARDIAN_AURA: {
    id: 'GUARDIAN_AURA', name: 'Guardian Aura', type: 'active', source: 'equipment',
    itemId: 'BLESSED_MACE', unlockLevel: null,
    description: 'Radiates protective force through the mace, striking a single foe. Scales with DEF.',
    icon: '🛡', effects: { powerMultiplier: 1.4, defScaling: 0.40, defBonus: 0.35, maxHpBonus: 0.15, atkBonus: 0.10 }, procChance: 0.45,
    narrative: 'radiates a guardian aura — the mace crashes down with holy force!',
  },
  SANCTUM_BARRIER: {
    id: 'SANCTUM_BARRIER', name: 'Sanctum Barrier', type: 'active', source: 'equipment',
    itemId: 'SANCTUM_HAMMER', unlockLevel: null,
    description: 'Slams the Sanctum Hammer into a foe with devastating holy force. Scales with DEF.',
    icon: '🏛', effects: { powerMultiplier: 1.6, defScaling: 0.55, defBonus: 0.45, maxHpBonus: 0.25, atkBonus: 0.15, critBonus: 0.05 }, procChance: 0.60,
    narrative: 'slams the Sanctum Hammer — holy force devastates the target!',
  },
  GUARDIAN_SLASH: {
    id: 'GUARDIAN_SLASH', name: 'Guardian Slash', type: 'active', source: 'equipment',
    itemId: 'GUARDIAN_BLADE', unlockLevel: null,
    description: 'Strikes with a guardian\'s resolve, balancing offense and defense. Scales with DEF.',
    icon: '🛡', effects: { powerMultiplier: 1.4, atkBonus: 0.30, defScaling: 0.40, defBonus: 0.25, maxHpBonus: 0.05 }, procChance: 0.45,
    narrative: 'strikes with a guardian\'s resolve!',
  },
  QUICK_DRAW: {
    id: 'QUICK_DRAW', name: 'Quick Draw', type: 'active', source: 'equipment',
    itemId: 'WINDRUNNER_QUIVER', unlockLevel: null,
    description: 'Wind-enchanted quiver feeds arrows faster, boosting attack speed.',
    icon: '💨', effects: { spdBonus: 0.30, atkBonus: 0.15, critChance: 0.10 }, procChance: 0.40,
    narrative: 'draws arrows with blinding speed from the Windrunner Quiver!',
  },
  SHADOW_SHOT: {
    id: 'SHADOW_SHOT', name: 'Shadow Quiver', type: 'active', source: 'equipment',
    itemId: 'SHADOWSTRIKE_QUIVER', unlockLevel: null,
    description: 'The Shadowstrike Quiver cloaks the archer in shadow, boosting speed and precision.',
    icon: '🌑', effects: { spdBonus: 0.25, critChance: 0.20, dodgeChance: 0.15 }, procChance: 0.45,
    narrative: 'draws from the Shadowstrike Quiver — shadows swirl and sharpen every sense!',
  },
  GALE_BARRAGE: {
    id: 'GALE_BARRAGE', name: 'Gale Winds', type: 'passive', source: 'equipment',
    itemId: 'GALE_QUIVER', unlockLevel: null,
    description: 'The Gale Quiver radiates storm energy, empowering the entire party with speed and force.',
    icon: '🌪', effects: { partySpdBonus: 0.15, partyAtkBonus: 0.10, critBonus: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  // ── Bard Lute Auras (Songweaver identity) ──
  SONGWEAVER: {
    id: 'SONGWEAVER', name: 'Songweaver', type: 'passive', source: 'equipment',
    itemId: 'ENCHANTED_LUTE', unlockLevel: null,
    description: 'The enchanted lute deepens the Regen Song. Regen Song potency +20%, party healing received +8%.',
    icon: '🎶', effects: { regenAmp: 0.20, partyHealBonus: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  SONGWEAVER_II: {
    id: 'SONGWEAVER_II', name: 'Songweaver II', type: 'passive', source: 'equipment',
    itemId: 'SIREN_HARP', unlockLevel: null,
    description: 'The siren harp amplifies restorative melodies. Regen Song potency +25%, party healing received +12%.',
    icon: '🎶', effects: { regenAmp: 0.25, partyHealBonus: 0.12 }, procChance: 1.0,
    narrative: null,
  },
  SIREN_SONG: {
    id: 'SIREN_SONG', name: 'Siren Song', type: 'active', source: 'equipment',
    itemId: 'SIREN_HARP', unlockLevel: null,
    description: 'Plays a mesmerizing Siren Song that enchants and heals.',
    icon: '🎵', effects: { powerMultiplier: 1.4, magBonus: 0.55, healBonus: 0.15, critBonus: 0.06, dodgeBonus: 0.09 }, procChance: 0.50,
    narrative: 'plays a mesmerizing Siren Song!',
  },
  // ── Bard Drum Auras (Wardrum identity) ──
  WARDRUM: {
    id: 'WARDRUM', name: 'Wardrum', type: 'passive', source: 'equipment',
    itemId: 'WAR_DRUM', unlockLevel: null,
    description: 'The war drum intensifies Discord. Discord DoT +25%, Discord ATK reduction +5%.',
    icon: '🥁', effects: { discordDotAmp: 0.25, discordAtkRedBonus: 0.05 }, procChance: 1.0,
    narrative: null,
  },
  WARDRUM_II: {
    id: 'WARDRUM_II', name: 'Wardrum II', type: 'passive', source: 'equipment',
    itemId: 'THUNDERDRUM', unlockLevel: null,
    description: 'The thunderdrum shakes enemies to their core. Discord DoT +35%, ATK reduction +8%, fumble chance +5%.',
    icon: '🥁', effects: { discordDotAmp: 0.35, discordAtkRedBonus: 0.08, discordFumbleBonus: 0.05 }, procChance: 1.0,
    narrative: null,
  },
  BATTLE_MARCH: {
    id: 'BATTLE_MARCH', name: 'Battle March', type: 'active', source: 'equipment',
    itemId: 'THUNDERDRUM', unlockLevel: null,
    description: 'Beats a rousing Battle March that rallies allies.',
    icon: '🥁', effects: { powerMultiplier: 1.4, magBonus: 0.35, defBonus: 0.20, healBonus: 0.15 }, procChance: 0.50,
    narrative: 'beats a rousing Battle March!',
  },
  TEMPLAR_MIGHT: {
    id: 'TEMPLAR_MIGHT', name: 'Templar Might', type: 'active', source: 'equipment',
    itemId: 'TEMPLAR_PLATE', unlockLevel: null,
    description: 'Channels the might of ancient templars.',
    icon: '✦', effects: { atkBonus: 0.20, defBonus: 0.15 }, procChance: 0.45,
    narrative: 'channels the might of ancient templars!',
  },
  TIGER_SPIRIT: {
    id: 'TIGER_SPIRIT', name: 'Tiger Spirit', type: 'active', source: 'equipment',
    itemId: 'TIGER_HIDE', unlockLevel: null,
    description: 'Channels the tiger\'s ferocity for deadly speed.',
    icon: '🐯', effects: { atkBonus: 0.25, spdBonus: 0.15 }, procChance: 0.45,
    narrative: 'channels the tiger\'s ferocity!',
  },
  DIAMOND_SKIN: {
    id: 'DIAMOND_SKIN', name: 'Diamond Skin', type: 'passive', source: 'equipment',
    itemId: 'STONE_SKIN_VEST', unlockLevel: null,
    description: 'Activates hardened Diamond Skin for unbreakable defense.',
    icon: '💎', effects: { defBonus: 0.35, dodgeChance: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  ARCANE_SURGE: {
    id: 'ARCANE_SURGE', name: 'Arcane Surge', type: 'active', source: 'equipment',
    itemId: 'ARCANE_VESTMENTS', unlockLevel: null,
    description: 'Unleashes an Arcane Surge of magical power.',
    icon: '✨', effects: { magBonus: 0.25, critChance: 0.15 }, procChance: 0.45,
    narrative: 'unleashes an Arcane Surge!',
  },
  DIVINE_WARD: {
    id: 'DIVINE_WARD', name: 'Divine Ward', type: 'active', source: 'equipment',
    itemId: 'SANCTIFIED_VESTMENTS', unlockLevel: null,
    description: 'Weaves a Divine Ward of holy protection.',
    icon: '🙏', effects: { defBonus: 0.25, magBonus: 0.15 }, procChance: 0.45,
    narrative: 'weaves a Divine Ward!',
  },
  SPIKED_BASH: {
    // Renamed from SHIELD_BASH to avoid collision with the Knight L1 class skill
    // of the same id — the equipment registry was spreading last and clobbering
    // the class entry, which emptied every Knight's attack pool in combat.
    id: 'SPIKED_BASH', name: 'Spiked Bash', type: 'active', source: 'equipment',
    itemId: 'SPIKED_SHIELD', unlockLevel: null,
    description: 'Bashes with shield force, combining offense and defense. Scales with DEF.',
    icon: '🎯', effects: { atkBonus: 0.20, defScaling: 0.35, defBonus: 0.15 }, procChance: 0.45,
    narrative: 'bashes with their shield!',
  },
  VOID_BURST: {
    id: 'VOID_BURST', name: 'Void Burst', type: 'active', source: 'equipment',
    itemId: 'ARCHMAGE_STAFF', unlockLevel: null,
    description: 'The Archmage Staff tears open a void rift, unleashing unstable magic across all enemies.',
    icon: '🌀', effects: { powerMultiplier: 1.2, magBonus: 0.50, critChance: 0.15 }, procChance: 0.50,
    narrative: 'tears open a void rift — unstable magic detonates across the enemy ranks!',
  },
  VOID_ATTUNEMENT: {
    id: 'VOID_ATTUNEMENT', name: 'Void Attunement', type: 'active', source: 'equipment',
    itemId: 'VOID_ORB', unlockLevel: null,
    description: 'The Void Orb resonates with dark energy, amplifying the wielder\'s magic and reflexes.',
    icon: '🌀', effects: { magBonus: 0.30, critChance: 0.15, dodgeBonus: 0.10 }, procChance: 0.45,
    narrative: 'attunes to the Void Orb — dark energy sharpens every spell!',
  },
  SANCTUARY: {
    id: 'SANCTUARY', name: 'Holy Sanctuary', type: 'passive', source: 'equipment',
    itemId: 'HOLY_ORB', unlockLevel: null,
    description: 'The Holy Orb creates a sanctuary of light for protection and healing.',
    icon: '☀', effects: { defBonus: 0.30, healBonus: 0.20 }, procChance: 1.0,
    narrative: null,
  },
  DRAGON_SPIRIT: {
    id: 'DRAGON_SPIRIT', name: 'Dragon Spirit', type: 'active', source: 'equipment',
    itemId: 'DRAGON_GI', unlockLevel: null,
    description: 'Channels the Dragon Spirit for fierce power.',
    icon: '🐲', effects: { atkBonus: 0.35, spdBonus: 0.25, critChance: 0.15 }, procChance: 0.55,
    narrative: 'channels the Dragon Spirit!',
  },
  AEGIS_AURA: {
    id: 'AEGIS_AURA', name: 'Aegis Aura', type: 'passive', source: 'equipment',
    itemId: 'AMULET_OF_AGES', unlockLevel: null,
    description: 'The Amulet of Ages radiates a permanent Aegis Aura, granting +25% DEF and +10% max HP.',
    icon: '✦', effects: { defBonus: 0.25, maxHpBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  RADIANT_STRIKE: {
    id: 'RADIANT_STRIKE', name: 'Radiant Strike', type: 'active', source: 'equipment',
    itemId: 'EXCALIBUR', unlockLevel: null,
    description: 'Channels blinding radiance into a devastating strike.',
    icon: '☀', effects: { powerMultiplier: 1.6, atkBonus: 0.70, critChance: 0.30, defPierce: 0.15 }, procChance: 0.60,
    narrative: 'channels blinding radiance into a devastating strike!',
  },
  DIVINE_OATH: {
    id: 'DIVINE_OATH', name: 'Divine Oath', type: 'active', source: 'equipment',
    itemId: 'OATHKEEPER', unlockLevel: null,
    description: 'Swears a Divine Oath where power and protection surge. Scales with DEF.',
    icon: '✝', effects: { powerMultiplier: 1.6, atkBonus: 0.45, defScaling: 0.50, defBonus: 0.40, maxHpBonus: 0.15 }, procChance: 0.60,
    narrative: 'swears a Divine Oath — power and protection surge!',
  },
  WORLD_CLEAVE: {
    id: 'WORLD_CLEAVE', name: 'World Cleave', type: 'active', source: 'equipment',
    itemId: 'RAGNAROK', unlockLevel: null,
    description: 'Cleaves with the force to split the world.',
    icon: '🌍', effects: { powerMultiplier: 1.6, atkBonus: 1.00, defPierce: 0.40, critChance: 0.20 }, procChance: 0.55,
    narrative: 'cleaves with the force to split the world!',
  },
  ASSASSINATION: {
    id: 'ASSASSINATION', name: 'Assassination', type: 'active', source: 'equipment',
    itemId: 'DEATHS_WHISPER', unlockLevel: null,
    description: 'Strikes from the void in an instant kill attempt.',
    icon: '💀', effects: { powerMultiplier: 1.6, atkBonus: 0.85, critChance: 0.40, dodgeChance: 0.20 }, procChance: 0.55,
    narrative: 'strikes from the void — an instant kill attempt!',
  },
  ASURA_FURY: {
    id: 'ASURA_FURY', name: 'Asura Fury', type: 'active', source: 'equipment',
    itemId: 'ASURA_CLAW', unlockLevel: null,
    description: 'Enters Asura Fury for a storm of devastating blows.',
    icon: '👹', effects: { powerMultiplier: 1.6, atkBonus: 0.90, spdBonus: 0.30, critChance: 0.30 }, procChance: 0.55,
    narrative: 'enters Asura Fury — a storm of devastating blows!',
  },

  // ── Monk 2H Staff Flowing Defense Procs ─────────────────────────────
  DEFLECTING_GUARD: {
    id: 'DEFLECTING_GUARD', name: 'Deflecting Guard', type: 'passive', source: 'equipment',
    itemId: 'HARDWOOD_BO', unlockLevel: null,
    description: 'The dense hardwood bo creates a natural defensive rhythm. A chance to deflect incoming blows, reflecting a portion back.',
    icon: '🪵', effects: { isDeflect: true, deflectChance: 0.15, dmgReduction: 0.25, reflectPct: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  // HEAVENLY_PALM (Retribution Stance, T4) and MONKEY_KING (Monkey King's Reflection, T5) defined above.
  CEL_COSMIC_REFLECTION: {
    id: 'CEL_COSMIC_REFLECTION', name: 'Cosmic Reflection', type: 'passive', source: 'equipment',
    itemId: 'CEL_STAFF_OF_THE_COSMOS', unlockLevel: null,
    description: 'The Staff of the Cosmos bends reality around the entire party. Attacks fold back on themselves, and allies move with cosmic grace.',
    icon: '🌌', effects: { isDeflect: true, deflectChance: 0.20, dmgReduction: 0.25, reflectPct: 0.20, partyWide: true, partyDodgeBonus: 0.08, selfDeflectChance: 0.30, selfDmgReduction: 0.30, selfReflectPct: 0.30 }, procChance: 1.0,
    narrative: null,
  },

  // ── Rogue Offhand DoT Procs (Poison) ──────────────────────────────────
  ENVENOM: {
    id: 'ENVENOM', name: 'Envenom', type: 'active', source: 'equipment',
    itemId: 'SERPENT_FANG', unlockLevel: null,
    description: 'The Serpent Fang injects venom that eats at the target over time, weakening their attacks.',
    icon: '🐍', effects: { dotAtkScale: 0.25, dotRounds: 2, atkDebuff: 0.10 }, procChance: 0.50,
    narrative: 'drives the Serpent Fang deep — venom courses through the wound!',
  },
  DEADLY_TOXIN: {
    id: 'DEADLY_TOXIN', name: 'Deadly Toxin', type: 'active', source: 'equipment',
    itemId: 'SCORPION_STILETTO', unlockLevel: null,
    description: 'The Scorpion Stiletto delivers a potent toxin that ravages the target and saps their strength.',
    icon: '🦂', effects: { dotAtkScale: 0.30, dotRounds: 3, atkDebuff: 0.15 }, procChance: 0.50,
    narrative: 'buries the Scorpion Stiletto — deadly toxin floods the wound!',
  },
  NEUROTOXIN: {
    id: 'NEUROTOXIN', name: 'Neurotoxin', type: 'active', source: 'equipment',
    itemId: 'BASILISK_KISS', unlockLevel: null,
    description: "The Basilisk's Kiss delivers a neurotoxin that paralyzes and corrodes from within.",
    icon: '☠', effects: { dotAtkScale: 0.35, dotRounds: 3, atkDebuff: 0.20 }, procChance: 0.55,
    narrative: "lands the Basilisk's Kiss — neurotoxin seizes the target's body!",
  },

  // ── Monk Offhand DoT Procs (Spirit/Chi Burn) ─────────────────────────
  SPIRIT_SCORCH: {
    id: 'SPIRIT_SCORCH', name: 'Spirit Scorch', type: 'active', source: 'equipment',
    itemId: 'SPIRIT_WRAPS', unlockLevel: null,
    description: 'The Spirit Wraps ignite chi energy that scorches the target from within, slowing their movements.',
    icon: '🔥', effects: { dotAtkScale: 0.25, dotRounds: 2, spdDebuff: 0.10 }, procChance: 0.50,
    narrative: 'channels chi through the Spirit Wraps — spiritual flame scorches the target!',
  },
  INNER_FIRE: {
    id: 'INNER_FIRE', name: 'Inner Fire', type: 'active', source: 'equipment',
    itemId: 'DEMON_PALM', unlockLevel: null,
    description: "The Demon's Palm ignites the target's chi meridians, burning from within and disrupting their flow.",
    icon: '👹', effects: { dotAtkScale: 0.30, dotRounds: 3, spdDebuff: 0.15 }, procChance: 0.50,
    narrative: "strikes with the Demon's Palm — inner fire erupts along the target's meridians!",
  },
  CHI_ERUPTION: {
    id: 'CHI_ERUPTION', name: 'Chi Eruption', type: 'active', source: 'equipment',
    itemId: 'ASTRAL_GAUNTLET', unlockLevel: null,
    description: 'The Astral Gauntlet ruptures the target\'s life force, causing devastating chi burns and sluggish movements.',
    icon: '💫', effects: { dotAtkScale: 0.35, dotRounds: 3, spdDebuff: 0.20 }, procChance: 0.55,
    narrative: 'unleashes the Astral Gauntlet — chi erupts from within the target!',
  },

  MONKEY_KING: {
    id: 'MONKEY_KING', name: "Monkey King's Reflection", type: 'passive', source: 'equipment',
    itemId: 'RUYI_JINGU', unlockLevel: null,
    description: "The Ruyi Jingu Bang radiates legendary force. A constant barrier deflects incoming blows with devastating reflection, and the wielder's ki hardens into a shield.",
    icon: '🐵', effects: { isDeflect: true, deflectChance: 0.25, dmgReduction: 0.35, reflectPct: 0.30, atkDebuff: 0.15, kiShieldPct: 0.05 }, procChance: 1.0,
    narrative: null,
  },
  CELESTIAL_VOLLEY: {
    id: 'CELESTIAL_VOLLEY', name: 'Celestial Volley', type: 'active', source: 'equipment',
    itemId: 'ARTEMIS_BOW', unlockLevel: null,
    description: 'Fires a Celestial Volley of arrows made of pure starlight.',
    icon: '🌠', effects: { powerMultiplier: 1.6, atkBonus: 0.80, spdBonus: 0.25, critChance: 0.30 }, procChance: 0.55,
    narrative: 'fires a Celestial Volley — arrows of pure starlight!',
  },
  ARCANE_CATACLYSM_EQ: {
    id: 'ARCANE_CATACLYSM_EQ', name: 'Cataclysm: Staff of Ages', type: 'active', source: 'equipment',
    itemId: 'STAFF_OF_AGES', unlockLevel: null,
    description: 'The Staff of Ages unleashes a devastating Arcane Cataclysm.',
    icon: '💥', effects: { powerMultiplier: 1.35, magBonus: 0.65, critChance: 0.25, defPierce: 0.20 }, procChance: 0.55,
    narrative: 'unleashes an Arcane Cataclysm!',
  },
  WORLD_BLESSING: {
    id: 'WORLD_BLESSING', name: 'World Blessing', type: 'active', source: 'equipment',
    itemId: 'STAFF_OF_DAWN', unlockLevel: null,
    description: 'Channels the World Blessing as divine power flows.',
    icon: '✧', effects: { powerMultiplier: 1.6, magBonus: 0.55, healBonus: 0.40, defBonus: 0.20 }, procChance: 0.60,
    narrative: 'channels the World Blessing — divine power flows!',
  },
  SONGWEAVER_III: {
    id: 'SONGWEAVER_III', name: 'Songweaver III', type: 'passive', source: 'equipment',
    itemId: 'ORPHEUS_LYRE', unlockLevel: null,
    description: 'The legendary lyre sings with divine resonance. Regen Song potency +35%, party healing received +15%.',
    icon: '🎶', effects: { regenAmp: 0.35, partyHealBonus: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  ORPHIC_HYMN: {
    id: 'ORPHIC_HYMN', name: 'Orphic Hymn', type: 'active', source: 'equipment',
    itemId: 'ORPHEUS_LYRE', unlockLevel: null,
    description: 'Performs the legendary Orphic Hymn with divine power.',
    icon: '🎼', effects: { powerMultiplier: 1.6, magBonus: 0.75, healBonus: 0.30, critBonus: 0.10, dodgeBonus: 0.15 }, procChance: 0.60,
    narrative: 'performs the legendary Orphic Hymn!',
  },
  WARDRUM_III: {
    id: 'WARDRUM_III', name: 'Wardrum III', type: 'passive', source: 'equipment',
    itemId: 'DRUMS_OF_ETERNITY', unlockLevel: null,
    description: 'The eternal drums devastate all who oppose. Discord DoT +50%, ATK reduction +10%, fumble chance +10%.',
    icon: '🥁', effects: { discordDotAmp: 0.50, discordAtkRedBonus: 0.10, discordFumbleBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  ETERNAL_RHYTHM: {
    id: 'ETERNAL_RHYTHM', name: 'Eternal Rhythm', type: 'active', source: 'equipment',
    itemId: 'DRUMS_OF_ETERNITY', unlockLevel: null,
    description: 'Beats the Eternal Rhythm as timeless power resonates.',
    icon: '🎶', effects: { powerMultiplier: 1.6, magBonus: 0.50, defBonus: 0.30, healBonus: 0.30 }, procChance: 0.60,
    narrative: 'beats the Eternal Rhythm — timeless power resonates!',
  },
  DRAGON_FURY: {
    id: 'DRAGON_FURY', name: 'Dragon Fury', type: 'active', source: 'equipment',
    itemId: 'DRAGON_PLATE', unlockLevel: null,
    description: 'Channels the fury of dragons.',
    icon: '🐉', effects: { atkBonus: 0.35, defBonus: 0.20, critChance: 0.15 }, procChance: 0.55,
    narrative: 'channels the fury of dragons!',
  },
  ADAMANTINE_WALL: {
    id: 'ADAMANTINE_WALL', name: 'Adamantine Wall', type: 'passive', source: 'equipment',
    itemId: 'ADAMANTINE_PLATE', unlockLevel: null,
    description: 'Becomes an Adamantine Wall of impenetrable defense.',
    icon: '🏔', effects: { defBonus: 0.50, maxHpBonus: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  SHADOW_DANCE: {
    id: 'SHADOW_DANCE', name: 'Shadow Dance', type: 'passive', source: 'equipment',
    itemId: 'PHANTOM_CHAIN', unlockLevel: null,
    description: 'Enters a Shadow Dance becoming untouchable.',
    icon: '💃', effects: { dodgeChance: 0.45, critChance: 0.20 }, procChance: 1.0,
    narrative: null,
  },
  CELESTIAL_AEGIS: {
    id: 'CELESTIAL_AEGIS', name: 'Celestial Aegis', type: 'passive', source: 'equipment',
    itemId: 'CELESTIAL_CHAIN', unlockLevel: null,
    description: 'Activates a Celestial Aegis of heavenly protection.',
    icon: '🛡', effects: { defBonus: 0.40, dodgeChance: 0.15, maxHpBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  NIRVANA_AURA: {
    id: 'NIRVANA_AURA', name: 'Nirvana Aura', type: 'passive', source: 'equipment',
    itemId: 'NIRVANA_SHROUD', unlockLevel: null,
    description: 'The Nirvana Shroud sustains a permanent aura of serene invulnerability: +30% DEF, +15% dodge, +8% max HP.',
    icon: '☮', effects: { defBonus: 0.30, dodgeChance: 0.15, maxHpBonus: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  CELESTIAL_WARD: {
    id: 'CELESTIAL_WARD', name: 'Celestial Ward', type: 'passive', source: 'equipment',
    itemId: 'CELESTIAL_ROBES', unlockLevel: null,
    description: 'Celestial Robes sustain a permanent ward of starlight: +30% DEF, +20% MAG.',
    icon: '⭐', effects: { defBonus: 0.30, magBonus: 0.20 }, procChance: 1.0,
    narrative: null,
  },
  AEGIS_COUNTER: {
    id: 'AEGIS_COUNTER', name: 'Aegis Counter', type: 'passive', source: 'equipment',
    itemId: 'AEGIS', unlockLevel: null,
    description: 'The Aegis channels its overwhelming power: +30% ATK, +25% DEF, +15% crit.',
    icon: '⚡', effects: { atkBonus: 0.30, defBonus: 0.25, critChance: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  ETERNAL_GUARD: {
    id: 'ETERNAL_GUARD', name: 'Eternal Guard', type: 'passive', source: 'equipment',
    itemId: 'WALL_OF_AGES', unlockLevel: null,
    description: 'Raises the Eternal Guard where nothing gets through.',
    icon: '🔰', effects: { defBonus: 0.65, maxHpBonus: 0.20 }, procChance: 1.0,
    narrative: null,
  },
  TEMPORAL_FLUX: {
    id: 'TEMPORAL_FLUX', name: 'Temporal Flux', type: 'active', source: 'equipment',
    itemId: 'ROBES_OF_ETERNITY', unlockLevel: null,
    description: 'The Robes of Eternity distort time, empowering the next spell with amplified magic and critical force.',
    icon: '⏳', pendingBuff: true, effects: { magBonus: 0.40, critChance: 0.15 }, procChance: 0.55,
    narrative: 'warps the flow of time — the next spell will arrive before it is cast!',
  },
  MYTHRIL_REFLEX: {
    id: 'MYTHRIL_REFLEX', name: 'Mythril Reflex', type: 'passive', source: 'equipment',
    itemId: 'MYTHRIL_CHAIN', unlockLevel: null,
    description: 'The Mythril Chain reacts to danger, hardening on impact and boosting evasion.',
    icon: '⚡', effects: { dodgeChance: 0.30, defBonus: 0.25, spdBonus: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  GENESIS_WARD: {
    id: 'GENESIS_WARD', name: 'Genesis Ward', type: 'active', source: 'equipment',
    itemId: 'ORB_OF_CREATION', unlockLevel: null,
    description: 'Creates a Genesis Ward of primordial power.',
    icon: '🌅', effects: { defBonus: 0.40, magBonus: 0.30, healBonus: 0.25 }, procChance: 0.55,
    narrative: 'creates a Genesis Ward of primordial power!',
  },
  ETERNITY_PULSE: {
    id: 'ETERNITY_PULSE', name: 'Eternity Pulse', type: 'passive', source: 'equipment',
    itemId: 'ORB_OF_ETERNITY', unlockLevel: null,
    description: 'The Orb of Eternity radiates infinite magical potential, permanently empowering the wielder.',
    icon: '💫', effects: { magBonus: 0.20, spdBonus: 0.15, critChance: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  BATTLE_FURY: {
    id: 'BATTLE_FURY', name: 'Battle Fury', type: 'active', source: 'equipment',
    itemId: 'AMULET_OF_FURY', unlockLevel: null,
    description: 'Enters a state of Battle Fury for overwhelming power.',
    icon: '🔥', effects: { powerMultiplier: 1.6, critChance: 0.15 }, procChance: 0.55,
    narrative: 'enters a state of Battle Fury!',
  },
  ARCANE_OVERFLOW: {
    id: 'ARCANE_OVERFLOW', name: 'Arcane Overflow', type: 'active', source: 'equipment',
    itemId: 'AMULET_OF_ARCANA', unlockLevel: null,
    description: 'Overflows with Arcane power for magical devastation.',
    icon: '💫', effects: { magBonus: 0.45, critChance: 0.20, spdBonus: 0.10 }, procChance: 0.55,
    narrative: 'overflows with Arcane power!',
  },
  GRACE_ETERNAL: {
    id: 'GRACE_ETERNAL', name: 'Grace Eternal', type: 'active', source: 'equipment',
    itemId: 'AMULET_OF_GRACE', unlockLevel: null,
    description: 'Channels Grace Eternal for divine protection and healing.',
    icon: '🕊', effects: { defBonus: 0.30, healBonus: 0.35, magBonus: 0.15 }, procChance: 0.55,
    narrative: 'channels Grace Eternal!',
  },
  WHISPER_DRAIN: {
    id: 'WHISPER_DRAIN', name: 'Whisper Drain', type: 'active', source: 'equipment',
    itemId: 'STAFF_OF_WHISPERS', unlockLevel: null,
    description: 'Staff of Whispers siphons life from the target. Deals MAG damage and heals.',
    icon: '🌑', effects: { powerMultiplier: 1.4, magBonus: 0.40, lifesteal: 0.30 }, procChance: 0.45,
    narrative: 'channels the Staff of Whispers — life force flows from the wound!',
  },
  DEATHRATTLE: {
    id: 'DEATHRATTLE', name: 'Deathrattle', type: 'active', source: 'equipment',
    itemId: 'DEATHRATTLE_STAFF', unlockLevel: null,
    description: 'Deathrattle Staff unleashes a death scream that damages and drains life from the target.',
    icon: '📯', effects: { magBonus: 0.50, powerMultiplier: 1.3, lifesteal: 0.35 }, procChance: 0.45,
    narrative: 'slams the Deathrattle Staff — a piercing death scream echoes across the battlefield!',
  },
  // ── Necromancer Scythe Auras (Death Lord identity) ──
  DEATHS_HARVEST: {
    id: 'DEATHS_HARVEST', name: "Death's Harvest", type: 'passive', source: 'equipment',
    itemId: 'GRAVE_REAPER', unlockLevel: null,
    description: 'The scythe empowers raised thralls. Minion damage +25%, minion HP +20%.',
    icon: '🪦', effects: { minionDamageBonus: 0.25, minionHpBonus: 0.20 }, procChance: 1.0,
    narrative: null,
  },
  DEATHS_HARVEST_II: {
    id: 'DEATHS_HARVEST_II', name: "Death's Harvest II", type: 'passive', source: 'equipment',
    itemId: 'SOUL_HARVESTER', unlockLevel: null,
    description: 'The scythe feeds harvested souls to the thrall. Minion damage +35%, minion HP +30%. Active: reaps a soul for MAG damage and shreds enemy DEF.',
    icon: '👤', effects: { minionDamageBonus: 0.35, minionHpBonus: 0.30 }, procChance: 1.0,
    narrative: null,
  },
  SOUL_REAP: {
    id: 'SOUL_REAP', name: 'Soul Reap', type: 'active', source: 'equipment',
    itemId: 'SOUL_HARVESTER', unlockLevel: null,
    description: 'Soul Harvester reaps a soul shard, dealing MAG damage and shredding 15% enemy DEF for 2 rounds.',
    icon: '👤', effects: { powerMultiplier: 1.4, magBonus: 0.40, defShred: 0.15, defShredRounds: 2 }, procChance: 0.45,
    narrative: 'reaps with the Soul Harvester — a ghostly echo tears free from the target!',
  },
  DEATHS_HARVEST_III: {
    id: 'DEATHS_HARVEST_III', name: "Death's Harvest III", type: 'passive', source: 'equipment',
    itemId: 'ABYSSAL_SCYTHE', unlockLevel: null,
    description: 'The abyssal scythe channels death itself into the thrall. Minion damage +50%, minion HP +40%, Blight tick damage +25%.',
    icon: '🌀', effects: { minionDamageBonus: 0.50, minionHpBonus: 0.40, blightAmp: 0.25 }, procChance: 1.0,
    narrative: null,
  },
  ABYSSAL_REAP: {
    id: 'ABYSSAL_REAP', name: 'Abyssal Reap', type: 'active', source: 'equipment',
    itemId: 'ABYSSAL_SCYTHE', unlockLevel: null,
    description: 'Abyssal Scythe tears open a rift, dealing massive MAG damage and shredding 20% enemy DEF for 2 rounds.',
    icon: '🌀', effects: { powerMultiplier: 1.5, magBonus: 0.50, defShred: 0.20, defShredRounds: 2 }, procChance: 0.50,
    narrative: 'sweeps the Abyssal Scythe — reality tears open and devours the target!',
  },
  SKULL_WHISPER: {
    id: 'SKULL_WHISPER', name: 'Skull Whisper', type: 'passive', source: 'equipment',
    itemId: 'WHISPERING_SKULL', unlockLevel: null,
    description: 'The Whispering Skull channels necrotic energy into a passive siphon. When the Necromancer deals damage, the party heals for 6% of each member\'s max HP.',
    icon: '💬', effects: { groupSiphon: true, siphonHealPct: 0.06 }, procChance: 1.0,
    narrative: null,
  },
  SOUL_SIPHON: {
    id: 'SOUL_SIPHON', name: 'Soul Siphon', type: 'passive', source: 'equipment',
    itemId: 'GRIMOIRE_OF_SOULS', unlockLevel: null,
    description: 'The Grimoire of Souls maintains a constant soul-drain. When the Necromancer deals damage, the party heals for 8% of each member\'s max HP.',
    icon: '📖', effects: { groupSiphon: true, siphonHealPct: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  DAMNED_CHORUS: {
    id: 'DAMNED_CHORUS', name: 'Damned Chorus', type: 'passive', source: 'equipment',
    itemId: 'SKULL_OF_THE_DAMNED', unlockLevel: null,
    description: 'The Skull of the Damned emits a constant chorus of anguished souls. When the Necromancer deals damage, the party heals for 12% of each member\'s max HP.',
    icon: '🗣', effects: { groupSiphon: true, siphonHealPct: 0.12 }, procChance: 1.0,
    narrative: null,
  },
  CEL_ASCENDANT_WRATH: {
    id: 'CEL_ASCENDANT_WRATH', name: 'Ascendant Wrath', type: 'active', source: 'equipment',
    itemId: 'CEL_DAWNBREAKER', unlockLevel: null,
    description: 'Dawnbreaker erupts with the fury of the first sunrise, dealing catastrophic radiant damage.',
    icon: '🌅', effects: { atkBonus: 0.40, critChance: 0.25, powerMultiplier: 1.8 }, procChance: 0.55,
    narrative: 'unleashes Ascendant Wrath — Dawnbreaker blazes with the fury of the first sunrise!',
  },
  CEL_ASCENDANT_AEGIS: {
    id: 'CEL_ASCENDANT_AEGIS', name: 'Ascendant Aegis', type: 'passive', source: 'equipment',
    itemId: 'CEL_ASCENDANT_PLATE', unlockLevel: null,
    description: 'The Ascendant Plate channels divine light, creating an impervious barrier.',
    icon: '✨', effects: { defBonus: 0.50, maxHpBonus: 0.30 }, procChance: 1.0,
    narrative: null,
  },
  CEL_ASCENDANT_RALLY: {
    id: 'CEL_ASCENDANT_RALLY', name: 'Ascendant Rally', type: 'passive', source: 'equipment',
    itemId: 'CEL_ASCENDANT_WARD', unlockLevel: null,
    description: 'The Ascendant Ward radiates courage, pushing every ally beyond their limits.',
    icon: '🏴', effects: { partyAtkBonus: 0.20, partyDefBonus: 0.15, partySpdBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  CEL_DESTINY_AURA: {
    id: 'CEL_DESTINY_AURA', name: "Destiny's Mantle", type: 'passive', source: 'equipment',
    itemId: 'CEL_CROWN_OF_THE_CHOSEN', unlockLevel: null,
    description: 'The Crown of the Chosen bathes the hero in the light of destiny, elevating all abilities.',
    icon: '👑', effects: { atkBonus: 0.20, defBonus: 0.20, spdBonus: 0.20, magBonus: 0.15, critBonus: 0.10, dodgeBonus: 0.10, maxHpBonus: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  CEL_WORLDSPLITTER: {
    id: 'CEL_WORLDSPLITTER', name: 'Worldsplitter', type: 'active', source: 'equipment',
    itemId: 'CEL_GODSLAYER', unlockLevel: null,
    description: 'The Godslayer cleaves through reality itself, delivering a cataclysmic blow that can end any foe.',
    icon: '💥', effects: { atkBonus: 0.50, critChance: 0.30, powerMultiplier: 2.0 }, procChance: 0.50,
    narrative: 'swings the Godslayer with world-ending force — reality cracks beneath the blow!',
  },
  CEL_SLAYERS_FERVOR: {
    id: 'CEL_SLAYERS_FERVOR', name: "Slayer's Fervor", type: 'passive', source: 'equipment',
    itemId: 'CEL_GODSLAYER', unlockLevel: null,
    description: 'The Godslayer demands total commitment. In return, it sharpens the wielder into a perfect weapon.',
    icon: '🔥', effects: { atkBonus: 0.20, critChance: 0.15, spdBonus: 0.12 }, procChance: 1.0,
    narrative: null,
  },
  CEL_BASTION_SMITE: {
    id: 'CEL_BASTION_SMITE', name: 'Bastion Smite', type: 'active', source: 'equipment',
    itemId: 'CEL_OATHSWORN', unlockLevel: null,
    description: 'Oathsworn channels the weight of an unbreakable vow into a devastating shockwave that strikes all enemies. Scales with DEF.',
    icon: '⚔', effects: { atkBonus: 0.35, defScaling: 0.65, defBonus: 0.20, powerMultiplier: 1.6 }, procChance: 0.55,
    narrative: 'delivers the Bastion Smite — Oathsworn unleashes an oath-bound shockwave across all enemies!',
  },
  CEL_BASTION_FORTRESS: {
    id: 'CEL_BASTION_FORTRESS', name: 'Living Fortress', type: 'passive', source: 'equipment',
    itemId: 'CEL_ETERNAL_BASTION', unlockLevel: null,
    description: 'The Eternal Bastion hardens to a substance beyond diamond, absorbing all punishment.',
    icon: '🏰', effects: { defBonus: 0.60, maxHpBonus: 0.40 }, procChance: 1.0,
    narrative: null,
  },
  CEL_BASTION_WARD: {
    id: 'CEL_BASTION_WARD', name: 'Infinite Aegis', type: 'passive', source: 'equipment',
    itemId: 'CEL_INFINITUM_SHIELD', unlockLevel: null,
    description: 'The Infinitum Shield extends its protection across all allies simultaneously.',
    icon: '🛡', effects: { partyDefBonus: 0.25, partyHpBonus: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  CEL_IMMOVABLE_AURA: {
    id: 'CEL_IMMOVABLE_AURA', name: 'The Immovable', type: 'passive', source: 'equipment',
    itemId: 'CEL_SENTINELS_ETERNITY', unlockLevel: null,
    description: "The Sentinel's Eternity makes the wearer an immovable anchor of divine protection.",
    icon: '⛰', effects: { defBonus: 0.30, maxHpBonus: 0.25, partyDefBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  CEL_ARCANUM_CATACLYSM: {
    id: 'CEL_ARCANUM_CATACLYSM', name: 'Infinite Cataclysm', type: 'active', source: 'equipment',
    itemId: 'CEL_INFINITY_STAFF', unlockLevel: null,
    description: 'The Infinity Staff tears open reality itself, unleashing a cataclysm of pure arcane energy.',
    icon: '💥', effects: { magBonus: 0.45, critChance: 0.20, powerMultiplier: 1.7 }, procChance: 0.55,
    narrative: 'channels Infinite Cataclysm — the Infinity Staff tears reality apart with impossible power!',
  },
  CEL_VOID_BARRIER: {
    id: 'CEL_VOID_BARRIER', name: 'Void Barrier', type: 'active', source: 'equipment',
    itemId: 'CEL_ROBES_OF_THE_VOID', unlockLevel: null,
    description: 'The Robes of the Void redirect all incoming damage through a dimensional rift.',
    icon: '🌀', effects: { defBonus: 0.40, magBonus: 0.30 }, procChance: 0.50,
    narrative: 'activates the Void Barrier — attacks phase through into nothingness!',
  },
  CEL_ARCANUM_RESONANCE: {
    id: 'CEL_ARCANUM_RESONANCE', name: 'Arcanum Resonance', type: 'passive', source: 'equipment',
    itemId: 'CEL_SINGULARITY_ORB', unlockLevel: null,
    description: 'The Singularity Orb amplifies all magical energy nearby to devastating levels.',
    icon: '🔮', effects: { partyMagBonus: 0.25, partyCritBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  CEL_OMNISCIENCE_AURA: {
    id: 'CEL_OMNISCIENCE_AURA', name: 'Omniscience', type: 'passive', source: 'equipment',
    itemId: 'CEL_DIADEM_OF_OMNISCIENCE', unlockLevel: null,
    description: 'The Diadem reveals all futures. Spells are cast with perfect foresight.',
    icon: '👁', effects: { magBonus: 0.25, spdBonus: 0.20, critChance: 0.18, critBonus: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  CEL_VOIDWALKER_STRIKE: {
    id: 'CEL_VOIDWALKER_STRIKE', name: 'Voidwalker Strike', type: 'active', source: 'equipment',
    itemId: 'CEL_VOIDFANG', unlockLevel: null,
    description: 'Voidfang phases through all defenses, striking directly at the target\'s essence.',
    icon: '🗡', effects: { atkBonus: 0.35, critChance: 0.30, powerMultiplier: 1.9 }, procChance: 0.60,
    narrative: 'executes the Voidwalker Strike — Voidfang phases through armor and strikes the soul!',
  },
  CEL_PHASE_SHIFT: {
    id: 'CEL_PHASE_SHIFT', name: 'Phase Shift', type: 'passive', source: 'equipment',
    itemId: 'CEL_WRAITHWEAVE', unlockLevel: null,
    description: 'Wraithweave shifts the rogue between dimensions, making them temporarily untouchable.',
    icon: '👻', effects: { spdBonus: 0.45, defBonus: 0.35 }, procChance: 1.0,
    narrative: null,
  },
  CEL_VOID_ECHO: {
    id: 'CEL_VOID_ECHO', name: 'Void Echo', type: 'passive', source: 'equipment',
    itemId: 'CEL_NULLBLADE', unlockLevel: null,
    description: 'Nullblade resonates through the void, sharpening every ally\'s senses and reflexes.',
    icon: '🌑', effects: { partySpdBonus: 0.20, partyCritBonus: 0.09, partyDodgeBonus: 0.06 }, procChance: 1.0,
    narrative: null,
  },
  CEL_VOIDVENOM: {
    id: 'CEL_VOIDVENOM', name: 'Voidvenom', type: 'active', source: 'equipment',
    itemId: 'CEL_NULLBLADE', unlockLevel: null,
    description: 'The Nullblade secretes venom distilled from the void between worlds. It dissolves not just flesh, but the target\'s will to fight.',
    icon: '☠', effects: { dotAtkScale: 0.42, dotRounds: 3, atkDebuff: 0.25 }, procChance: 0.60,
    narrative: 'drives the Nullblade deep — void-venom floods the wound, dissolving flesh and will alike!',
  },
  CEL_SHADOW_DIMENSION: {
    id: 'CEL_SHADOW_DIMENSION', name: 'Shadow Dimension', type: 'passive', source: 'equipment',
    itemId: 'CEL_ECLIPSE_PENDANT', unlockLevel: null,
    description: 'The Eclipse Pendant anchors the rogue partially in the shadow dimension. Always half-invisible.',
    icon: '🌘', effects: { spdBonus: 0.25, critBonus: 0.15, dodgeBonus: 0.10, critChance: 0.20, atkBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  CEL_DIVINE_JUDGEMENT: {
    id: 'CEL_DIVINE_JUDGEMENT', name: "Dawn's Judgement", type: 'active', source: 'equipment',
    itemId: 'CEL_SCEPTER_OF_DAWN', unlockLevel: null,
    description: 'The Scepter of Dawn channels the wrath of the heavens, passing judgement upon the unworthy.',
    icon: '⚡', effects: { magBonus: 0.35, atkBonus: 0.20, powerMultiplier: 1.7 }, procChance: 0.55,
    narrative: "calls down Dawn's Judgement — the Scepter of Dawn sears evil with holy radiance!",
  },
  CEL_SANCTIFIED_RADIANCE: {
    id: 'CEL_SANCTIFIED_RADIANCE', name: 'Sanctified Radiance', type: 'passive', source: 'equipment',
    itemId: 'CEL_SCEPTER_OF_DAWN', unlockLevel: null,
    description: 'The Scepter of Dawn bathes the party in sanctified light. Persistent HoT: ~38% of Cleric MAG per round to all allies.',
    icon: '☀', effects: { clericRegen: true, clericRegenScale: 0.38 }, procChance: 1.0,
    narrative: null,
  },
  CEL_DIVINE_SHIELD: {
    id: 'CEL_DIVINE_SHIELD', name: 'Radiant Aegis', type: 'passive', source: 'equipment',
    itemId: 'CEL_VESTMENTS_OF_GRACE', unlockLevel: null,
    description: 'The Vestments of Grace form a radiant aegis that heals as it protects.',
    icon: '🛐', effects: { defBonus: 0.45, maxHpBonus: 0.35, healBonus: 0.20 }, procChance: 1.0,
    narrative: null,
  },
  CEL_MIRACULOUS_BLESSING: {
    id: 'CEL_MIRACULOUS_BLESSING', name: 'Miraculous Blessing', type: 'passive', source: 'equipment',
    itemId: 'CEL_TOME_OF_MIRACLES', unlockLevel: null,
    description: 'The Tome of Miracles opens, showering the entire party with divine protection and power.',
    icon: '📖', effects: { partyDefBonus: 0.20, partyHpBonus: 0.15, partyMagBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  CEL_RESURRECTION_AURA: {
    id: 'CEL_RESURRECTION_AURA', name: 'Resurrection Aura', type: 'passive', source: 'equipment',
    itemId: 'CEL_HALO_OF_THE_BLESSED', unlockLevel: null,
    description: 'The Halo radiates constant divine energy. The wounded are mended, the weary are restored.',
    icon: '😇', effects: { magBonus: 0.25, defBonus: 0.20, maxHpBonus: 0.20, healBonus: 0.25 }, procChance: 1.0,
    narrative: null,
  },
  CEL_CELESTIAL_BARRAGE: {
    id: 'CEL_CELESTIAL_BARRAGE', name: 'Celestial Barrage', type: 'active', source: 'equipment',
    itemId: 'CEL_STARFALL_BOW', unlockLevel: null,
    description: 'The Starfall Bow fires a barrage of star-forged arrows that rain from the heavens.',
    icon: '🌠', effects: { atkBonus: 0.40, spdBonus: 0.25, powerMultiplier: 1.8 }, procChance: 0.55,
    narrative: 'unleashes a Celestial Barrage — stars fall from the heavens, each one a devastating arrow!',
  },
  CEL_STELLAR_CLOAK: {
    id: 'CEL_STELLAR_CLOAK', name: 'Stellar Cloak', type: 'passive', source: 'equipment',
    itemId: 'CEL_STARHIDE_MANTLE', unlockLevel: null,
    description: 'The Starhide Mantle blazes with starlight, deflecting attacks into the void between stars.',
    icon: '🌟', effects: { defBonus: 0.40, spdBonus: 0.30 }, procChance: 1.0,
    narrative: null,
  },
  CEL_STARFIRE_VOLLEY: {
    id: 'CEL_STARFIRE_VOLLEY', name: 'Starfire Volley', type: 'passive', source: 'equipment',
    itemId: 'CEL_CONSTELLATION_QUIVER', unlockLevel: null,
    description: 'The Constellation Quiver supplies starfire arrows to every ally, raining celestial destruction.',
    icon: '🎆', effects: { partyAtkBonus: 0.20, partySpdBonus: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  CEL_NORTH_STAR_AURA: {
    id: 'CEL_NORTH_STAR_AURA', name: 'North Star', type: 'passive', source: 'equipment',
    itemId: 'CEL_POLARIS_PENDANT', unlockLevel: null,
    description: 'Guided by the North Star. Every shot finds its mark. Every step finds its path.',
    icon: '⭐', effects: { atkBonus: 0.25, spdBonus: 0.20, critBonus: 0.20, critChance: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  CEL_SONG_OF_CREATION: {
    id: 'CEL_SONG_OF_CREATION', name: 'Song of Creation', type: 'active', source: 'equipment',
    itemId: 'CEL_LYRE_OF_CREATION', unlockLevel: null,
    description: 'The Lyre plays the melody that created the universe. Reality reshapes at its command.',
    icon: '🎵', effects: { magBonus: 0.30, critBonus: 0.10, dodgeBonus: 0.15, powerMultiplier: 1.7 }, procChance: 0.55,
    narrative: 'plays the Song of Creation — the melody that birthed the universe reshapes the battlefield!',
  },
  CEL_COSMIC_HARMONY: {
    id: 'CEL_COSMIC_HARMONY', name: 'Cosmic Harmony', type: 'active', source: 'equipment',
    itemId: 'CEL_VESTMENTS_OF_COSMOS', unlockLevel: null,
    description: 'The cosmos harmonizes around the wearer, turning all discord into protection.',
    icon: '🪐', effects: { defBonus: 0.35, magBonus: 0.30 }, procChance: 0.50,
    narrative: 'enters Cosmic Harmony — the fabric of the cosmos shields against all harm!',
  },
  CEL_RHYTHM_OF_WORLDS: {
    id: 'CEL_RHYTHM_OF_WORLDS', name: 'Rhythm of Worlds', type: 'active', source: 'equipment',
    itemId: 'CEL_DRUM_OF_ETERNITY', unlockLevel: null,
    description: 'The Drum beats with the heartbeat of infinite worlds, synchronizing and empowering all allies.',
    icon: '🥁', effects: { partyAtkBonus: 0.18, partyDefBonus: 0.18, partyMagBonus: 0.18, partySpdBonus: 0.18, powerMultiplier: 1.5 }, procChance: 0.50,
    narrative: 'strikes the Rhythm of Worlds — the heartbeat of infinite worlds empowers every ally!',
  },
  CEL_WARDRUM: {
    id: 'CEL_WARDRUM', name: 'Eternal Wardrum', type: 'passive', source: 'equipment',
    itemId: 'CEL_DRUM_OF_ETERNITY', unlockLevel: null,
    description: 'The Drum of Eternity crushes the spirit of all who oppose. Discord DoT +60%, ATK reduction +15%, fumble chance +15%, party SPD +8%.',
    icon: '💫', effects: { discordDotAmp: 0.60, discordAtkRedBonus: 0.15, discordFumbleBonus: 0.15, partySpdBonus: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  CEL_SYMPHONY_AURA: {
    id: 'CEL_SYMPHONY_AURA', name: 'Eternal Symphony', type: 'passive', source: 'equipment',
    itemId: 'CEL_MAESTROS_SIGNET', unlockLevel: null,
    description: 'The grand symphony plays eternally. All who hear it are elevated beyond mortal limits.',
    icon: '🎶', effects: { magBonus: 0.18, critBonus: 0.09, dodgeBonus: 0.13, spdBonus: 0.18, atkBonus: 0.10, defBonus: 0.10, partyCritBonus: 0.05, partyDodgeBonus: 0.07 }, procChance: 1.0,
    narrative: null,
  },
  CEL_SONGWEAVER: {
    id: 'CEL_SONGWEAVER', name: "Muse's Songweaver", type: 'passive', source: 'equipment',
    itemId: 'CEL_LYRE_OF_CREATION', unlockLevel: null,
    description: 'The Lyre of Creation hums with the voice of the First Muse. Regen Song potency +40%, party healing received +20%. Regen Song never rolls lower.',
    icon: '✨', effects: { regenAmp: 0.40, partyHealBonus: 0.20, regenNeverLower: true }, procChance: 1.0,
    narrative: null,
  },
  CEL_TRANSCENDENT_STRIKE: {
    id: 'CEL_TRANSCENDENT_STRIKE', name: 'Transcendent Strike', type: 'active', source: 'equipment',
    itemId: 'CEL_FISTS_OF_NIRVANA', unlockLevel: null,
    description: 'The Fists of Nirvana strike with the accumulated weight of ten thousand years of meditation.',
    icon: '👊', effects: { atkBonus: 0.40, spdBonus: 0.25, powerMultiplier: 1.9 }, procChance: 0.60,
    narrative: 'delivers the Transcendent Strike — fists blur with the speed and weight of enlightenment!',
  },
  CEL_ABSOLUTE_FLOW: {
    id: 'CEL_ABSOLUTE_FLOW', name: 'Absolute Flow', type: 'passive', source: 'equipment',
    itemId: 'CEL_GI_OF_THE_ABSOLUTE', unlockLevel: null,
    description: 'The Gi of the Absolute allows the monk to flow around every attack with perfect precision.',
    icon: '🌊', effects: { defBonus: 0.40, spdBonus: 0.35 }, procChance: 1.0,
    narrative: null,
  },
  CEL_INFINITE_PALM: {
    id: 'CEL_INFINITE_PALM', name: 'Infinite Palm', type: 'passive', source: 'equipment',
    itemId: 'CEL_PALM_OF_THE_INFINITE', unlockLevel: null,
    description: 'The Palm radiates chi across the battlefield, quickening and strengthening every ally.',
    icon: '🤲', effects: { partySpdBonus: 0.20, partyAtkBonus: 0.15, partyDefBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  CEL_ASTRAL_IGNITION: {
    id: 'CEL_ASTRAL_IGNITION', name: 'Astral Ignition', type: 'active', source: 'equipment',
    itemId: 'CEL_PALM_OF_THE_INFINITE', unlockLevel: null,
    description: 'The Palm of the Infinite ignites the target\'s astral body. Their very soul burns, and their movements slow to a crawl.',
    icon: '💫', effects: { dotAtkScale: 0.42, dotRounds: 3, spdDebuff: 0.25 }, procChance: 0.60,
    narrative: 'strikes with the Palm of the Infinite — astral fire erupts from the target\'s core, burning their very essence!',
  },
  CEL_NIRVANA_AURA: {
    id: 'CEL_NIRVANA_AURA', name: 'Nirvana', type: 'passive', source: 'equipment',
    itemId: 'CEL_CHAKRA_OF_ENLIGHTENMENT', unlockLevel: null,
    description: 'True enlightenment achieved. Body, mind, and spirit in absolute harmony.',
    icon: '☯', effects: { atkBonus: 0.20, defBonus: 0.20, spdBonus: 0.20, maxHpBonus: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  CEL_SIPHON_OF_SOULS: {
    id: 'CEL_SIPHON_OF_SOULS', name: 'Siphon of Souls', type: 'passive', source: 'equipment',
    itemId: 'CEL_SOULWEAVER', unlockLevel: null,
    description: 'The Soulweaver weaves an unbreakable soul-drain across the battlefield. When the Necromancer deals damage, the party heals for 16% of each member\'s max HP.',
    icon: '🩸', effects: { groupSiphon: true, siphonHealPct: 0.16 }, procChance: 1.0,
    narrative: null,
  },
  CEL_SOULWEAVER_DRAIN: {
    id: 'CEL_SOULWEAVER_DRAIN', name: 'Soul Drain', type: 'active', source: 'equipment',
    itemId: 'CEL_SOULWEAVER', unlockLevel: null,
    description: 'The Soulweaver fires a devastating bolt of stolen life force. On hit, each living ally heals for 10% of their max HP.',
    icon: '🩸', effects: { powerMultiplier: 1.6, magBonus: 0.60, partyLeechPct: 0.10 }, procChance: 0.50,
    narrative: 'channels the Soulweaver — a bolt of stolen life force tears through the enemy!',
  },
  CEL_DEATHS_HARVEST: {
    id: 'CEL_DEATHS_HARVEST', name: "Death's Dominion", type: 'passive', source: 'equipment',
    itemId: 'CEL_MORTALITYS_END', unlockLevel: null,
    description: "Mortality's End transforms the thrall into a lord of death. Minion damage +60%, minion HP +50%, thrall attacks hit ALL enemies, Blight tick damage +30%, party MAG +8%.",
    icon: '💀', effects: { minionDamageBonus: 0.60, minionHpBonus: 0.50, minionAoe: true, blightAmp: 0.30, partyMagBonus: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  CEL_LICHBORNE: {
    id: 'CEL_LICHBORNE', name: 'Lichborne', type: 'active', source: 'equipment',
    itemId: 'CEL_SHROUD_OF_THE_LICH', unlockLevel: null,
    description: 'The Shroud remembers undeath. Grants massive DEF and HP, channeling lich-like resilience.',
    icon: '🧟', effects: { defBonus: 0.45, maxHpBonus: 0.30, magBonus: 0.15 }, procChance: 0.50,
    narrative: 'wraps in the Shroud of the Lich — flesh hardens, eyes glow with undying power!',
  },
  CEL_ETERNAL_WHISPER: {
    id: 'CEL_ETERNAL_WHISPER', name: 'Eternal Whisper', type: 'active', source: 'equipment',
    itemId: 'CEL_SKULL_OF_ETERNAL_WHISPERS', unlockLevel: null,
    description: 'The Skull reveals the exact moment of each enemy\'s death, dealing devastating targeted damage.',
    icon: '👁', effects: { magBonus: 0.60, critChance: 0.30, powerMultiplier: 1.6 }, procChance: 0.50,
    narrative: 'holds aloft the Skull of Eternal Whispers — it speaks the true name of death!',
  },
  CEL_ETERNAL_SIPHON: {
    id: 'CEL_ETERNAL_SIPHON', name: 'Eternal Siphon', type: 'passive', source: 'equipment',
    itemId: 'CEL_SKULL_OF_ETERNAL_WHISPERS', unlockLevel: null,
    description: 'The Skull of Eternal Whispers sustains an unbreakable soul-drain. When the Necromancer deals damage, the party heals for 16% of each member\'s max HP.',
    icon: '💬', effects: { groupSiphon: true, siphonHealPct: 0.16 }, procChance: 1.0,
    narrative: null,
  },
  CEL_SOUL_ANCHOR: {
    id: 'CEL_SOUL_ANCHOR', name: 'Soul Anchor', type: 'passive', source: 'equipment',
    itemId: 'CEL_PHYLACTERY_OF_SOULS', unlockLevel: null,
    description: 'The Phylactery anchors the Necromancer\'s soul. MAG +20%, maxHP +15%, DEF +10%. Minion damage +15%.',
    icon: '⚓', effects: { magBonus: 0.20, maxHpBonus: 0.15, defBonus: 0.10, minionDamageBonus: 0.15 }, procChance: 1.0,
    narrative: null,
  },
};
