// Class masteries — passive bonuses unlocked at high levels (source: mastery)

export const MASTERIES = {
  HERO_M_VERSATILITY: {
    id: 'HERO_M_VERSATILITY', name: 'Versatility', type: 'passive', source: 'mastery',
    classId: 'HERO', unlockLevel: 4,
    description: 'ATK +8%, DEF +5%. A well-rounded foundation.',
    icon: '🎖', effects: { atkBonus: 0.08, defBonus: 0.05 }, procChance: 1.0,
    narrative: null,
  },
  HERO_M_BLADE_MASTERY: {
    // RETIRED — Hero L8 mastery slot now hosts Rally Cry (lifted from skill track per §4.2).
    id: 'HERO_M_BLADE_MASTERY', name: 'Blade Mastery (Legacy)', type: 'legacy', source: 'legacy',
    classId: 'HERO', unlockLevel: 99,
    description: 'LEGACY — Retired Hero L8 passive. Rally Cry now fills this mastery slot.',
    icon: '🗡', effects: { atkBonus: 0.12, critChance: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  HERO_M_LEADERS_AURA: {
    id: 'HERO_M_LEADERS_AURA', name: 'Leader\'s Aura', type: 'passive', source: 'mastery',
    classId: 'HERO', unlockLevel: 12,
    description: 'PARTY MASTERY — All allies gain +3% ATK, +2% DEF, and +2% SPD from the Hero\'s leadership.',
    icon: '👑', effects: { partyAtkBonus: 0.03, partyDefBonus: 0.02, partySpdBonus: 0.02 }, procChance: 1.0,
    narrative: null,
  },
  HERO_M_INSPIRING_PRESENCE: {
    id: 'HERO_M_INSPIRING_PRESENCE', name: 'Inspiring Presence', type: 'passive', source: 'mastery',
    classId: 'HERO', unlockLevel: 16,
    description: 'The Hero\'s presence inspires all. Party ATK +10%, SPD +8%, CRIT +4%, DODGE +3%.',
    icon: '✨', effects: { partyAtkBonus: 0.10, partySpdBonus: 0.08, partyCritBonus: 0.04, partyDodgeBonus: 0.03 }, procChance: 1.0,
    narrative: null,
  },
  HERO_M_CHOSEN_ONE: {
    id: 'HERO_M_CHOSEN_ONE', name: 'The Chosen One', type: 'passive', source: 'mastery',
    classId: 'HERO', unlockLevel: 20,
    description: 'EPIC — All stats +12%. The Hero\'s destiny is fulfilled.',
    icon: '🌠', effects: { atkBonus: 0.12, defBonus: 0.12, spdBonus: 0.12, magBonus: 0.12, critBonus: 0.06, dodgeBonus: 0.06, maxHpBonus: 0.12 }, procChance: 1.0,
    narrative: null,
  },
  KNIGHT_M_IRON_SKIN: {
    id: 'KNIGHT_M_IRON_SKIN', name: 'Iron Skin', type: 'passive', source: 'mastery',
    classId: 'KNIGHT', unlockLevel: 4,
    description: 'DEF +10%, MAX HP +8%.',
    icon: '🪨', effects: { defBonus: 0.10, maxHpBonus: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  KNIGHT_M_SHIELD_MASTERY: {
    id: 'KNIGHT_M_SHIELD_MASTERY', name: 'Shield Mastery (Legacy)', type: 'legacy', source: 'legacy',
    classId: 'KNIGHT', unlockLevel: 99,
    description: 'RETIRED — L8 mastery slot now hosts the lifted Shield Wall active. Kept for save compatibility.',
    icon: '🛡', effects: { defBonus: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  KNIGHT_M_IRON_AURA: {
    id: 'KNIGHT_M_IRON_AURA', name: 'Iron Aura', type: 'passive', source: 'mastery',
    classId: 'KNIGHT', unlockLevel: 12,
    description: 'PARTY MASTERY — All allies gain +3% DEF, +2% MAX HP, and +1% ATK from the Knight\'s protective presence.',
    icon: '🔰', effects: { partyDefBonus: 0.03, partyHpBonus: 0.02, partyAtkBonus: 0.01 }, procChance: 1.0,
    narrative: null,
  },
  KNIGHT_M_FORTIFICATION: {
    id: 'KNIGHT_M_FORTIFICATION', name: 'Fortification (Legacy)', type: 'legacy', source: 'legacy',
    classId: 'KNIGHT', unlockLevel: 99,
    description: 'RETIRED — L16 mastery slot now hosts the lifted Taunt active. Kept for save compatibility.',
    icon: '🏛', effects: { defBonus: 0.20, maxHpBonus: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  KNIGHT_M_AEGIS_ETERNAL: {
    id: 'KNIGHT_M_AEGIS_ETERNAL', name: 'Aegis Eternal', type: 'passive', source: 'mastery',
    classId: 'KNIGHT', unlockLevel: 20,
    description: 'EPIC — DEF +30%, MAX HP +25%, ATK +10%. The ultimate defensive form.',
    icon: '⚜', effects: { defBonus: 0.30, maxHpBonus: 0.25, atkBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  MAGE_M_PHASE_SHIFT: {
    id: 'MAGE_M_PHASE_SHIFT', name: 'Phase Shift', type: 'active', source: 'mastery',
    classId: 'MAGE', unlockLevel: 4,
    description: 'REACTIVE — When the Mage drops below 40% HP or would be killed, they phase out of reality for 2 rounds (untargetable). Lethal hits leave the Mage at 1 HP. 4-round cooldown.',
    icon: '🌀', effects: { phaseShiftDuration: 2, phaseShiftThreshold: 0.40 }, procChance: 1.0,
    reactive: true, cooldown: 4,
    narrative: null,
  },
  MAGE_M_ARCANE_FOCUS: {
    id: 'MAGE_M_ARCANE_FOCUS', name: 'Arcane Focus', type: 'passive', source: 'mastery',
    classId: 'MAGE', unlockLevel: 8,
    description: 'MAG +30%, SPD +5%. Deep arcane reserves and sharper magical focus.',
    icon: '✧', effects: { magBonus: 0.30, spdBonus: 0.05 }, procChance: 1.0,
    narrative: null,
  },
  MAGE_M_ARCANE_EMPOWERMENT: {
    id: 'MAGE_M_ARCANE_EMPOWERMENT', name: 'Arcane Empowerment', type: 'passive', source: 'mastery',
    classId: 'MAGE', unlockLevel: 12,
    description: 'PARTY MASTERY — All allies gain +3% MAG, +2% CRIT, +1% SPD, and +1% ATK from arcane energy.',
    icon: '💫', effects: { partyMagBonus: 0.03, partyCritBonus: 0.02, partySpdBonus: 0.01, partyAtkBonus: 0.01 }, procChance: 1.0,
    narrative: null,
  },
  MAGE_M_MANA_SHIELD: {
    id: 'MAGE_M_MANA_SHIELD', name: 'Mana Shield', type: 'passive', source: 'mastery',
    classId: 'MAGE', unlockLevel: 16,
    description: 'Arcane wards replace armor. DEF +15%, MAG +10%.',
    icon: '🔮', effects: { defBonus: 0.15, magBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  MAGE_M_INFINITE_MANA: {
    id: 'MAGE_M_INFINITE_MANA', name: 'Infinite Mana', type: 'passive', source: 'mastery',
    classId: 'MAGE', unlockLevel: 20,
    description: 'EPIC — MAG +35%, crit chance +12%, SPD +8%. Bottomless magical reserves.',
    icon: '♾', effects: { magBonus: 0.35, critChance: 0.12, spdBonus: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  ROGUE_M_NIMBLE_FINGERS: {
    id: 'ROGUE_M_NIMBLE_FINGERS', name: 'Nimble Fingers', type: 'passive', source: 'mastery',
    classId: 'ROGUE', unlockLevel: 4,
    description: 'SPD +8%, CRIT +5%, DODGE +3%.',
    icon: '🤏', effects: { spdBonus: 0.08, critBonus: 0.05, dodgeBonus: 0.03 }, procChance: 1.0,
    narrative: null,
  },
  ROGUE_M_EVASIVE_MANEUVER: {
    id: 'ROGUE_M_EVASIVE_MANEUVER', name: 'Evasive Maneuver', type: 'passive', source: 'mastery',
    classId: 'ROGUE', unlockLevel: 8,
    description: 'Slip through attacks with practiced ease. DODGE +18%, SPD +10%.',
    icon: '💨', effects: { dodgeBonus: 0.18, spdBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  ROGUE_M_SHADOW_NETWORK: {
    id: 'ROGUE_M_SHADOW_NETWORK', name: 'Shadow Network', type: 'passive', source: 'mastery',
    classId: 'ROGUE', unlockLevel: 12,
    description: 'PARTY MASTERY — All allies gain +2% SPD, +2% CRIT, and +2% DODGE from the Rogue\'s connections.',
    icon: '🕸', effects: { partySpdBonus: 0.02, partyCritBonus: 0.02, partyDodgeBonus: 0.02 }, procChance: 1.0,
    narrative: null,
  },
  ROGUE_M_LETHALITY: {
    id: 'ROGUE_M_LETHALITY', name: 'Lethality (Legacy)', type: 'legacy', source: 'legacy',
    classId: 'ROGUE', unlockLevel: 99,
    description: 'RETIRED — L16 mastery slot now hosts the lifted Smoke Bomb active. Kept for save compatibility.',
    icon: '☠', effects: { atkBonus: 0.18, critChance: 0.10, spdBonus: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  ROGUE_M_DEATH_DEALER: {
    id: 'ROGUE_M_DEATH_DEALER', name: 'Death Dealer', type: 'passive', source: 'mastery',
    classId: 'ROGUE', unlockLevel: 20,
    description: 'EPIC — ATK +25%, crit chance +18%, dodge +15%. The ultimate assassin.',
    icon: '🃏', effects: { atkBonus: 0.25, critChance: 0.18, dodgeChance: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  CLERIC_M_HOLY_DEVOTION: {
    id: 'CLERIC_M_HOLY_DEVOTION', name: 'Holy Devotion', type: 'passive', source: 'mastery',
    classId: 'CLERIC', unlockLevel: 4,
    description: 'MAG +8%, DEF +6%.',
    icon: '🙏', effects: { magBonus: 0.08, defBonus: 0.06 }, procChance: 1.0,
    narrative: null,
  },
  CLERIC_M_DIVINE_GRACE: {
    id: 'CLERIC_M_DIVINE_GRACE', name: 'Divine Grace (Legacy)', type: 'legacy', source: 'legacy',
    classId: 'CLERIC', unlockLevel: 99,
    description: 'RETIRED — L8 mastery slot now hosts the lifted Divine Shield active. Kept for save compatibility.',
    icon: '🌿', effects: { magBonus: 0.12, maxHpBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  CLERIC_M_SANCTUARY: {
    id: 'CLERIC_M_SANCTUARY', name: 'Sanctuary', type: 'passive', source: 'mastery',
    classId: 'CLERIC', unlockLevel: 12,
    description: 'PARTY MASTERY — All allies gain +2% MAX HP, +2% DEF, +2% SPD, and +2% CRIT from the Cleric\'s sanctuary.',
    icon: '☀', effects: { partyHpBonus: 0.02, partyDefBonus: 0.02, partySpdBonus: 0.02, partyCritBonus: 0.02 }, procChance: 1.0,
    narrative: null,
  },
  CLERIC_M_INNER_LIGHT: {
    id: 'CLERIC_M_INNER_LIGHT', name: 'Inner Light (Legacy)', type: 'legacy', source: 'legacy',
    classId: 'CLERIC', unlockLevel: 99,
    description: 'RETIRED — L16 mastery slot now hosts the lifted Resurrection active. Kept for save compatibility.',
    icon: '💡', effects: { magBonus: 0.20, defBonus: 0.12, maxHpBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  CLERIC_M_DIVINE_VESSEL: {
    id: 'CLERIC_M_DIVINE_VESSEL', name: 'Divine Vessel', type: 'passive', source: 'mastery',
    classId: 'CLERIC', unlockLevel: 20,
    description: 'EPIC — MAG +30%, DEF +15%, MAX HP +20%. A conduit of divine power.',
    icon: '🏆', effects: { magBonus: 0.30, defBonus: 0.15, maxHpBonus: 0.20 }, procChance: 1.0,
    narrative: null,
  },
  RANGER_M_KEEN_EYE: {
    id: 'RANGER_M_KEEN_EYE', name: 'Keen Eye', type: 'passive', source: 'mastery',
    classId: 'RANGER', unlockLevel: 4,
    description: 'ATK +8%, CRIT +6%.',
    icon: '👁', effects: { atkBonus: 0.08, critBonus: 0.06 }, procChance: 1.0,
    narrative: null,
  },
  RANGER_M_NATURE_BOND: {
    id: 'RANGER_M_NATURE_BOND', name: 'Nature Bond', type: 'passive', source: 'mastery',
    classId: 'RANGER', unlockLevel: 8,
    description: 'Attuned to the wilds. Gold +12%, EXP +12%, SPD +8%, party DODGE +6%.',
    icon: '🌿', effects: { goldBonus: 0.12, expBonus: 0.12, spdBonus: 0.08, partyDodgeBonus: 0.06 }, procChance: 1.0,
    narrative: null,
  },
  RANGER_M_SCOUTS_ADVANTAGE: {
    id: 'RANGER_M_SCOUTS_ADVANTAGE', name: 'Scout\'s Advantage', type: 'passive', source: 'mastery',
    classId: 'RANGER', unlockLevel: 12,
    description: 'PARTY MASTERY — All allies gain +3% ATK, +2% SPD, and +2% CRIT from the Ranger\'s recon.',
    icon: '🔭', effects: { partyAtkBonus: 0.03, partySpdBonus: 0.02, partyCritBonus: 0.02 }, procChance: 1.0,
    narrative: null,
  },
  RANGER_M_HUNTER_INSTINCT: {
    id: 'RANGER_M_HUNTER_INSTINCT', name: 'Hunter Instinct (Legacy)', type: 'legacy', source: 'legacy',
    classId: 'RANGER', unlockLevel: 99,
    description: 'RETIRED — L16 mastery slot now hosts the lifted Camouflage active. Kept for save compatibility.',
    icon: '🦅', effects: { atkBonus: 0.18, spdBonus: 0.12, critChance: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  RANGER_M_APEX_PREDATOR: {
    id: 'RANGER_M_APEX_PREDATOR', name: 'Apex Predator', type: 'passive', source: 'mastery',
    classId: 'RANGER', unlockLevel: 20,
    description: 'EPIC — ATK +25%, SPD +15%, crit +12%, +20% gold/exp. Top of the food chain.',
    icon: '🐻', effects: { atkBonus: 0.25, spdBonus: 0.15, critChance: 0.12, goldBonus: 0.20, expBonus: 0.20 }, procChance: 1.0,
    narrative: null,
  },
  BARD_M_CHARM: {
    id: 'BARD_M_CHARM', name: 'Charm', type: 'passive', source: 'mastery',
    classId: 'BARD', unlockLevel: 4,
    description: 'CRIT +5%, DODGE +7%, gold +8%. Natural charisma.',
    icon: '💝', effects: { critBonus: 0.05, dodgeBonus: 0.07, goldBonus: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  BARD_M_SYMPHONY_OF_WAR: {
    id: 'BARD_M_SYMPHONY_OF_WAR', name: 'Symphony of War', type: 'passive', source: 'mastery',
    classId: 'BARD', unlockLevel: 8,
    description: 'A stirring martial anthem empowers the whole party. Party ATK +15%, SPD +12%, CRIT +8%.',
    icon: '🎺', effects: { partyAtkBonus: 0.15, partySpdBonus: 0.12, partyCritBonus: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  BARD_M_FORTISSIMO: {
    id: 'BARD_M_FORTISSIMO', name: 'Fortissimo', type: 'passive', source: 'mastery',
    classId: 'BARD', unlockLevel: 12,
    description: 'PARTY MASTERY — All allies gain +2% ATK, +2% SPD, +2% CRIT, +1% DODGE, and +1% DEF from the Bard\'s performance.',
    icon: '🔊', effects: { partyAtkBonus: 0.02, partySpdBonus: 0.02, partyCritBonus: 0.02, partyDodgeBonus: 0.01, partyDefBonus: 0.01 }, procChance: 1.0,
    narrative: null,
  },
  BARD_M_VIRTUOSO: {
    id: 'BARD_M_VIRTUOSO', name: 'Virtuoso (Legacy)', type: 'legacy', source: 'legacy',
    classId: 'BARD', unlockLevel: 99,
    description: 'RETIRED — L16 mastery slot now hosts the new Magnum Opus active. Kept for save compatibility.',
    icon: '🎹', effects: { magBonus: 0.15, critBonus: 0.06, dodgeBonus: 0.09, spdBonus: 0.10, goldBonus: 0.12 }, procChance: 1.0,
    narrative: null,
  },
  BARD_M_LEGEND_OF_SONG: {
    id: 'BARD_M_LEGEND_OF_SONG', name: 'Legend of Song', type: 'passive', source: 'mastery',
    classId: 'BARD', unlockLevel: 20,
    description: 'EPIC — MAG +20%, CRIT +10%, DODGE +15%, SPD +15%, gold +20%. Songs echo through eternity.',
    icon: '🏅', effects: { magBonus: 0.20, critBonus: 0.10, dodgeBonus: 0.15, spdBonus: 0.15, goldBonus: 0.20 }, procChance: 1.0,
    narrative: null,
  },
  MONK_M_BALANCE: {
    id: 'MONK_M_BALANCE', name: 'Balance', type: 'passive', source: 'mastery',
    classId: 'MONK', unlockLevel: 4,
    description: 'ATK +5%, DEF +5%, SPD +5%, MAG +5%, DODGE +5%. The path to balance begins.',
    icon: '⚖', effects: { atkBonus: 0.05, defBonus: 0.05, spdBonus: 0.05, magBonus: 0.05, dodgeBonus: 0.05 }, procChance: 1.0,
    narrative: null,
  },
  MONK_M_IRON_BODY: {
    id: 'MONK_M_IRON_BODY', name: 'Iron Body', type: 'passive', source: 'mastery',
    classId: 'MONK', unlockLevel: 8,
    description: 'ATK +10%, DEF +10%, dodge +8%.',
    icon: '🏋', effects: { atkBonus: 0.10, defBonus: 0.10, dodgeChance: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  MONK_M_KI_RESONANCE: {
    id: 'MONK_M_KI_RESONANCE', name: 'Ki Resonance', type: 'passive', source: 'mastery',
    classId: 'MONK', unlockLevel: 12,
    description: 'PARTY MASTERY — All allies gain +3% ATK, +3% DEF, +3% SPD, and +3% CRIT from the Monk\'s ki.',
    icon: '🧘', effects: { partyAtkBonus: 0.03, partyDefBonus: 0.03, partySpdBonus: 0.03, partyCritBonus: 0.03 }, procChance: 1.0,
    narrative: null,
  },
  MONK_M_ENLIGHTENMENT: {
    id: 'MONK_M_ENLIGHTENMENT', name: 'Enlightenment', type: 'passive', source: 'mastery',
    classId: 'MONK', unlockLevel: 16,
    description: 'ATK +10%, DEF +10%, SPD +10%, MAG +10%, DODGE +10%.',
    icon: '🪷', effects: { atkBonus: 0.10, defBonus: 0.10, spdBonus: 0.10, magBonus: 0.10, dodgeBonus: 0.10 }, procChance: 1.0,
    narrative: null,
  },
  MONK_M_TRANSCENDENCE: {
    id: 'MONK_M_TRANSCENDENCE', name: 'Transcendence', type: 'passive', source: 'mastery',
    classId: 'MONK', unlockLevel: 20,
    description: 'EPIC — All core stats +15%, dodge +15%. Perfect martial enlightenment.',
    icon: '🌅', effects: { atkBonus: 0.15, defBonus: 0.15, spdBonus: 0.15, magBonus: 0.15, dodgeBonus: 0.15, dodgeChance: 0.15 }, procChance: 1.0,
    narrative: null,
  },
  NECRO_M_GRAVE_CHILL: {
    id: 'NECRO_M_GRAVE_CHILL', name: 'Grave Chill', type: 'passive', source: 'mastery',
    classId: 'NECROMANCER', unlockLevel: 4,
    description: 'MAG +8%, SPD +5%. Early power ramp — the cold of the grave seeps into every spell.',
    icon: '🥶', effects: { magBonus: 0.08, spdBonus: 0.05 }, procChance: 1.0,
    narrative: null,
  },
  NECRO_M_SOUL_HARVEST: {
    id: 'NECRO_M_SOUL_HARVEST', name: 'Soul Harvest', type: 'passive', source: 'mastery',
    classId: 'NECROMANCER', unlockLevel: 8,
    description: 'MAG +12%, CRIT +8%. Feeding on the energy of fallen souls.',
    icon: '👁', effects: { magBonus: 0.12, critChance: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  NECRO_M_SHROUD_OF_DECAY: {
    id: 'NECRO_M_SHROUD_OF_DECAY', name: 'Shroud of Decay', type: 'passive', source: 'mastery',
    classId: 'NECROMANCER', unlockLevel: 12,
    description: 'PARTY MASTERY — All allies gain +4% MAG, +3% CRIT, +3% DEF, and +2% ATK. Enemies that strike party members take necrotic reflect damage scaled from the Necromancer\'s MAG.',
    icon: '💜', effects: { partyMagBonus: 0.04, partyCritBonus: 0.03, partyDefBonus: 0.03, partyAtkBonus: 0.02, necroticReflect: true }, procChance: 1.0,
    narrative: null,
  },
  NECRO_M_UNDYING_WILL: {
    id: 'NECRO_M_UNDYING_WILL', name: 'Undying Will', type: 'passive', source: 'mastery',
    classId: 'NECROMANCER', unlockLevel: 16,
    description: 'MAG +18%, DEF +10%, maxHP +8%. Growing harder to put down.',
    icon: '🦴', effects: { magBonus: 0.18, defBonus: 0.10, maxHpBonus: 0.08 }, procChance: 1.0,
    narrative: null,
  },
  NECRO_M_LORD_OF_THE_DEAD: {
    id: 'NECRO_M_LORD_OF_THE_DEAD', name: 'Lord of the Dead', type: 'passive', source: 'mastery',
    classId: 'NECROMANCER', unlockLevel: 20,
    description: 'EPIC — MAG +30%, CRIT +12%, ATK +10%, maxHP +10%. Raised minions deal 25% more damage.',
    icon: '👑', effects: { magBonus: 0.30, critChance: 0.12, atkBonus: 0.10, maxHpBonus: 0.10, minionDamageBonus: 0.25 }, procChance: 1.0,
    narrative: null,
  },
};
